# Site Settings
lang   : en
title  : 
tagline: Mengaldo Lab
description: >
  This is our research website.
author   : Gianmarco Mengaldo
linkedin : https://www.linkedin.com/in/gianmarco-m/?originalSubdomain=sg
favicon  : /images/logo-no-background.png
permalink: pretty
# theme_color: '#eeeeee'
# theme_color: "#216778"
theme_color: '#485ec6'


# pagination settings
paginate: 5
paginate_path: "/news/page:num"

## plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true
sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-code-here
markdown: kramdown
highlighter: rouge
kramdown:
  parse_block_html: true
