# Site Settings
lang: en
title: Mengaldo Lab
tagline: Mengaldo Lab
# email: your-email@domain.com
description: >
  This is our research website.
permalink: pretty
favicon: /images/Logo.jpg
#hide_share_buttons: true
#theme_color: '#eeeeee'
# fixed_navbar: top
# direction: one of <ltr, rtl, auto>, default: ltr

# Pagination settings
paginate: 5
paginate_path: "/news/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false`
  # to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname:

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - ['jekyll/scholar']
  
scholar:

  last_name: Bryngelson
  first_name: [Spencer H.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true
sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-code-here
markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      # author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true


series: news
footer_menu: footer_menu

collections:
  research:
    output: true
    layout: research
    image: https://via.placeholder.com/800x600
    show_sidebar: false
